# Generated by Django 3.2.12 on 2022-06-25 14:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='postgmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 6, 25, 15, 15, 23, 854853))),
                ('founder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='postgmon.author')),
            ],
        ),
    ]
