# Generated by Django 3.2.12 on 2022-06-25 14:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postgmon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postgmodels',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 15, 23, 48, 313569)),
        ),
        migrations.AlterField(
            model_name='postgmodels',
            name='founder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='postgmon.author'),
        ),
    ]
