# Generated by Django 3.2.12 on 2022-06-25 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgmon', '0002_auto_20220625_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgmodels',
            name='founder',
        ),
        migrations.AlterField(
            model_name='postgmodels',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 15, 25, 40, 491523)),
        ),
    ]
