# Generated by Django 3.2.12 on 2022-06-25 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgmon', '0003_auto_20220625_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgmodels',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 15, 30, 35, 265163), null=True),
        ),
    ]
