# Generated by Django 3.2.12 on 2022-06-25 15:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postgmon', '0004_alter_postgmodels_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgmodels',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='postgmodels',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 16, 22, 43, 610108), null=True),
        ),
    ]
