# Generated by Django 3.2.12 on 2022-06-25 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgmon', '0005_auto_20220625_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgmodels',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 16, 57, 52, 683684)),
        ),
    ]
